### PR TITLE
Fix home path

### LINKED ISSUE #34: Panick at exit with Ctrl-D
Hello! I've downloaded the repository, and run `cargo run`. The error:

```bash
➜  oursh git:(master) cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s                                                                                                             
     Running `target/debug/oursh`
oursh-0.3$ exit
thread 'main' panicked at 'error cannot find history: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
```

I tried manually creating a `~/.oursh_history` file, but the error persists.

System info:
OS: Fedora 28
`rustc` version: 1.31.0-nightly

### PR DESCRIPTION
**Pull request by dread-uo**
I've used the `home_dir` function of the `dirs` crate to handle the history file path safely.

This should close #34.

### CODE REVIEW

File: src/repl/history.rs [hunk 1]
```diff
@@ -68,8 +68,10 @@ impl History {
 
     pub fn load() -> Self {
         let mut history = History(None, vec![]);
-        if Path::new("/home/nixpulvis/.oursh_history").exists() {
-            let mut f = File::open("/home/nixpulvis/.oursh_history")
+        let home_dir = dirs::home_dir().unwrap();
```
Comment (nixpulvis) [inline src/repl/history.rs]:
```suggestion
        let home = env::var("HOME").expect("HOME variable not set");
```

Comment (nixpulvis) [reply src/repl/history.rs]: The documentation for the deprecated `std::env::home_dir` does say to do it your way, however that's if you want the same functionality exactly. Since we don't care about windows, I don't think we need this.

Comment (nixpulvis) [reply src/repl/history.rs]: https://github.com/nixpulvis/oursh/blob/master/src/program/builtin.rs#L46

Comment (dread-uo) [reply src/repl/history.rs]: Makes sense; changed!

**Comment by nixpulvis** [comment]
Thanks for making this change, and let me know if there's anything else you need.

I'm currently working on the lexer #22 (so we can recognize whitespace and lex WORDS).
